### ISSUE TITLE
Generating the WcfMonoClient/Web Services/Reference.cs via MonoDevelop?

### ISSUE THREAD

**Issue by pascalhaakmat** [billyaraujo/wcf-mono#1]
Hi,

When I try to re-generate the service code for the client, I get an empty Reference.cs:

```
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WcfMonoClient.localhost_2 {

}
```

But in your repo, the file `WcfMonoClient/Service\ References/localhost/Reference.cs` looks okay. Can you tell me how you generated it? Via MonoDevelop or Xamarin or ...?

Thanks,
Pascal

**Comment by bjaraujo** [comment]
Hi Pascal,

That reference was created using Xamarin on windows.
Also make sure service is running on the specified address.
